  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - serverbase
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/docker/nginx/sites-enabled:/sites-enabled
      - /mnt/docker/nginx/conf:/conf.d
      - /mnt/docker/nginx/log:/var/log/nginx
      - /mnt/docker/letsencrypt/certstore:/certs
      - /mnt/docker/nginx/passwds:/passwds

networks:
  serverbase:
    driver: 'bridge' 
