---
- hosts: all

  vars_prompt:

    - name: confirm_uninstall
      prompt: "Do you really want to uninstall ecloud? This will delete all data and can not be reverted [yes/no]"
      private: no

    - name: delete_certs
      prompt: "Delete certificates? Select 'no' if you want to reinstall ecloud [yes/no]"
      private: no

  tasks:
  - name: end play if no confirmation was given
    debug:
      msg: "Uninstall cancelled, doing nothing"
    when: not confirm_uninstall|bool

  - meta: end_play
    when: not confirm_uninstall|bool

  - name: stop docker-compose
    docker_compose:
      project_src: /mnt/repo-base/
      state: absent

  - name: delete data
    file: path={{item.path}} state=absent
    with_items:
      - { path: '/mnt/repo-base/docker-compose.yml'}
      - { path: '/mnt/repo-base/volumes/'}
      - { path: '/mnt/repo-base/config-static/' }
      - { path: '/mnt/repo-base/scripts/' }
      - { path: '/mnt/repo-base/config-dynamic/.installation-complete' }
      - { path: '/mnt/repo-base/config-dynamic/automx/' }
      - { path: '/mnt/repo-base/config-dynamic/letsencrypt/autorenew/' }
      - { path: '/mnt/repo-base/config-dynamic/letsencrypt/acme-challenge/' }
      - { path: '/mnt/repo-base/config-dynamic/nextcloud/' }
      - { path: '/mnt/repo-base/config-dynamic/nginx/' }

  - name: delete entire ecloud folder
    file: path='/mnt/repo-base/' state=absent
    when: delete_certs|bool

  - name: remove certbot cronjob
    cron:
      name=ssl-renew
      state=absent

# TODO: might want to remove docker and other packages, but we dont know if they are used elsewhere
