
  nginx:
    image: registry.gitlab.e.foundation:5000/e/infra/docker-nginx:1.15
    container_name: nginx
    restart: always
    networks:
      - serverbase
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/repo-base/config-dynamic/nginx/sites-enabled:/etc/nginx/conf.d/
      - /mnt/repo-base/config-static/nginx/params:/etc/nginx/params/
      - /mnt/repo-base/config-dynamic/letsencrypt/certstore:/certs
      - /mnt/repo-base/config-dynamic/nginx/passwds:/passwds
      - /mnt/repo-base/config-dynamic/letsencrypt/acme-challenge:/etc/letsencrypt/acme-challenge

networks:
  serverbase:
    driver: 'bridge' 
