
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:5.2.6.3
    container_name: onlyoffice-documentserver
    stdin_open: true
    restart: always
    networks:
      - serverbase
    volumes:
     - /mnt/repo-base/volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
     - /mnt/repo-base/volumes/onlyoffice/DocumentServer/logs:/var/log/onlyoffice
  onlyoffice-mail-server:
    image: onlyoffice/mailserver:1.6.35
    container_name: onlyoffice-mail-server
    stdin_open: true
    hostname: onlyoffice.${DOMAIN}
    restart: always
    networks:
      - serverbase
    volumes:
     - /mnt/repo-base/volumes/onlyoffice/MailServer/data:/var/vmail
     - /mnt/repo-base/volumes/onlyoffice/MailServer/data/certs:/etc/pki/tls/mailserver
     - /mnt/repo-base/volumes/onlyoffice/MailServer/logs:/var/log
     - /mnt/repo-base/volumes/onlyoffice/MailServer/mysql:/var/lib/mysql
  onlyoffice-community-server:
    image: onlyoffice/communityserver:9.6.5.771
    container_name: onlyoffice-community-server
    restart: always
    networks:
      - serverbase
    ports:
      - 5222:5222
    environment:
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
      - MAIL_SERVER_DB_HOST=onlyoffice-mail-server
    volumes:
     - /mnt/repo-base/volumes/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data
     - /mnt/repo-base/volumes/onlyoffice/CommunityServer/mysql:/var/lib/mysql
     - /mnt/repo-base/volumes/onlyoffice/CommunityServer/logs:/var/log/onlyoffice
     - /mnt/repo-base/volumes/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServerData
    depends_on:
      - onlyoffice-documentserver
      - onlyoffice-mail-server
