version: '2.1'

services:
  eelomailserver:
    image: hardware/mailserver:1.1-stable
    container_name: mailserver
    domainname: ${DOMAIN} # Mail server A/MX/FQDN & reverse PTR = mail.${DOMAIN}.
    hostname: mail
    restart: always
    networks:
      - serverbase
    ports:
      - "25:25"       # SMTP                - Required
      - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=${DBPASS}
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}
      - ADD_DOMAINS=${ADD_DOMAINS}
      - ENABLE_POP3=${ENABLE_POP3}
      - DISABLE_RATELIMITING=${DISABLE_RATELIMITING}
      # Full list of options: https://github.com/hardware/mailserver#environment-variables
    volumes:
      - /mnt/repo-base/volumes/mail:/var/mail
      - /mnt/repo-base/config-dynamic/letsencrypt/certstore:/etc/letsencrypt
      - /mnt/repo-base/config-static/mail/dovecot/10-mail.conf:/etc/dovecot/conf.d/10-mail.conf
      - /mnt/repo-base/config-static/mail/dovecot/90-quota.conf:/etc/dovecot/conf.d/90-quota.conf
      - /mnt/repo-base/config-static/mail/dovecot/90-sieve.conf:/etc/dovecot/conf.d/90-sieve.conf
    depends_on:
      - mariadb
      - redis

  postfixadmin:
    image: registry.gitlab.e.foundation:5000/e/infra/docker-postfixadmin:0.1.2
    container_name: postfixadmin
    domainname: ${DOMAIN}
    hostname: mail
    restart: always
    networks:
      - serverbase
    environment:
      - DBPASS=${DBPASS}
      - POSTFIXADMIN_SSH_PASSWORD=${POSTFIXADMIN_SSH_PASSWORD}
    depends_on:
      - eelomailserver
      - mariadb

  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    networks:
      - serverbase
    environment:
      # Note: These variables are only used for the first start. Later changes are ignored.
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PFDB_DB}
      - MYSQL_USER=${PFDB_USR}
      - MYSQL_PASSWORD=${DBPASS}
    volumes:
      - /mnt/repo-base/volumes/mysql/db:/var/lib/mysql
      - /mnt/repo-base/config-dynamic/nextcloud/database:/docker-entrypoint-initdb.d

  redis:
    image: redis:4.0-alpine
    container_name: redis
    restart: always
    networks:
      - serverbase
    command: redis-server --appendonly yes
    volumes:
      - /mnt/repo-base/volumes/redis/db:/data

  pma:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: pma
    restart: always
    networks:
      - serverbase
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
  accounts:
        image: registry.gitlab.e.foundation:5000/e/infra/docker-welcome:0.2.0
        container_name: accounts
        environment:
         - DOMAINS=${VHOSTS_ACCOUNTS}
         - IS_WELCOME=true
         - PFDB_HOST=mariadb
         - PFDB_DB=${PFDB_DB}
         - PFDB_USR=${PFDB_USR}
         - PFDB_PW=${DBPASS}
         - SMTP_HOST=${DOMAIN}
         - SMTP_FROM=${SMTP_FROM}
         - SMTP_PW=${SMTP_PW}
         - CREATE_ACCOUNT_PASSWORD=${CREATE_ACCOUNT_PASSWORD}
        restart: always
        networks:
          - serverbase
        volumes:
              - /mnt/repo-base/volumes/accounts:/var/accounts
        depends_on:
              - mariadb

  nextcloud:
    image: nextcloud:14.0
    container_name: nextcloud
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NC}
      - MYSQL_USER=${MYSQL_USER_NC}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_NC}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    restart: always
    networks:
      - serverbase
    volumes:
      - /mnt/repo-base/volumes/nextcloud/html:/var/www/html/
      - /mnt/repo-base/volumes/nextcloud/custom_apps:/var/www/html/custom_apps/
      - /mnt/repo-base/volumes/nextcloud/config:/var/www/html/config/
      - /mnt/repo-base/volumes/nextcloud/data:/var/www/html/data/
    depends_on:
      - mariadb

  automx:
    image: registry.gitlab.e.foundation:5000/e/infra/docker-mailstack:automx-0.1.0
    container_name: automx
    hostname: automx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - DOMAIN=${DOMAIN}
      - HOSTNAME=automx
    restart: always
    networks:
      - serverbase
    volumes:
      - /mnt/repo-base/config-dynamic/automx/automx.conf:/etc/automx.conf

  create-account:
    image: registry.gitlab.e.foundation:5000/e/infra/docker-create-account:0.1.3
    container_name: create-account
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - POSTFIXADMIN_SSH_PASSWORD=${POSTFIXADMIN_SSH_PASSWORD}
      - DOMAIN=${DOMAIN}
      - CREATE_ACCOUNT_PASSWORD=${CREATE_ACCOUNT_PASSWORD}
    networks:
      - serverbase
    depends_on:
      - nextcloud
      - postfixadmin
